### ISSUE TITLE
Eslint issue error

### ISSUE THREAD

**Issue by fswizard** [laststance/create-react-app-vite#667]
![image](https://github.com/laststance/create-react-app-vite/assets/91833579/32d89c2f-3f22-4065-a823-dc3fde6a24b2)
We have such error when execute `npm run eslint:fix`. I think it is due the eslint module version. So I used eslint alpha version and fixed it.
I hope this solution helps other devs. :)

**Comment by ryota-murakami** [comment]
@fswizard Please seutp again or down glade prettier to `^2.8.8`.
Your prettier might 3.0.0. is not support eslint.

**Comment by fswizard** [comment]
@ryota-murakami  thx
